/**
 * 数据库初始化数据定义
 * @description 定义初始化所需的角色、菜单、关联数据
 */

import type { NewSysConfig } from './schema/system-config'

/**
 * 基础角色数据
 */
export const ROLES = [
  {
    id: 1,
    roleName: '管理员',
    sort: 1,
    status: 1,
    remark: '拥有大部分管理权限',
  },
] as const

/**
 * 系统菜单数据
 * menuType: D-目录 M-菜单 B-按钮
 */
export const MENUS = [
  // 仪表盘
  {
    id: 26,
    parentId: 0,
    menuType: 'M' as const,
    menuName: '仪表盘',
    permission: null,
    path: '/dashboard',
    component: 'dashboard/page',
    icon: 'LayoutDashboardFilled',
    sort: 9999,
    visible: 1,
    status: 1,
  },
  // 系统管理目录
  {
    id: 1,
    parentId: 0,
    menuType: 'D' as const,
    menuName: '系统管理',
    permission: null,
    path: null,
    component: null,
    icon: 'SettingsFilled',
    sort: 0,
    visible: 1,
    status: 1,
  },
  // 用户管理
  {
    id: 2,
    parentId: 1,
    menuType: 'M' as const,
    menuName: '用户管理',
    permission: 'system:admin:list',
    path: '/system/admin',
    component: 'system/admin/page',
    icon: 'UserFilled',
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 3,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '查询管理员',
    permission: 'system:admin:query',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 4,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '新增管理员',
    permission: 'system:admin:create',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 5,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '编辑管理员',
    permission: 'system:admin:update',
    path: null,
    component: null,
    icon: null,
    sort: 2,
    visible: 1,
    status: 1,
  },
  {
    id: 6,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '删除管理员',
    permission: 'system:admin:delete',
    path: null,
    component: null,
    icon: null,
    sort: 3,
    visible: 1,
    status: 1,
  },
  {
    id: 7,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '重置密码',
    permission: 'system:admin:resetPwd',
    path: null,
    component: null,
    icon: null,
    sort: 4,
    visible: 1,
    status: 1,
  },
  {
    id: 8,
    parentId: 2,
    menuType: 'B' as const,
    menuName: '分配角色',
    permission: 'system:admin:assignRole',
    path: null,
    component: null,
    icon: null,
    sort: 5,
    visible: 1,
    status: 1,
  },
  // 角色管理
  {
    id: 9,
    parentId: 1,
    menuType: 'M' as const,
    menuName: '角色管理',
    permission: 'system:role:list',
    path: '/system/role',
    component: 'system/role/page',
    icon: 'ShieldFilled',
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 10,
    parentId: 9,
    menuType: 'B' as const,
    menuName: '新增角色',
    permission: 'system:role:create',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 11,
    parentId: 9,
    menuType: 'B' as const,
    menuName: '查询角色',
    permission: 'system:role:query',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 12,
    parentId: 9,
    menuType: 'B' as const,
    menuName: '编辑角色',
    permission: 'system:role:update',
    path: null,
    component: null,
    icon: null,
    sort: 2,
    visible: 1,
    status: 1,
  },
  {
    id: 13,
    parentId: 9,
    menuType: 'B' as const,
    menuName: '删除角色',
    permission: 'system:role:delete',
    path: null,
    component: null,
    icon: null,
    sort: 3,
    visible: 1,
    status: 1,
  },
  {
    id: 14,
    parentId: 9,
    menuType: 'B' as const,
    menuName: '分配菜单',
    permission: 'system:role:assignMenu',
    path: null,
    component: null,
    icon: null,
    sort: 4,
    visible: 1,
    status: 1,
  },
  // 菜单管理
  {
    id: 15,
    parentId: 1,
    menuType: 'M' as const,
    menuName: '菜单管理',
    permission: 'system:menu:list',
    path: '/system/menu',
    component: 'system/menu/page',
    icon: 'IconArticleFilled',
    sort: 2,
    visible: 1,
    status: 1,
  },
  {
    id: 16,
    parentId: 15,
    menuType: 'B' as const,
    menuName: '新增菜单',
    permission: 'system:menu:create',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 17,
    parentId: 15,
    menuType: 'B' as const,
    menuName: '编辑菜单',
    permission: 'system:menu:update',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 18,
    parentId: 15,
    menuType: 'B' as const,
    menuName: '删除菜单',
    permission: 'system:menu:delete',
    path: null,
    component: null,
    icon: null,
    sort: 2,
    visible: 1,
    status: 1,
  },
  // 操作日志
  {
    id: 19,
    parentId: 1,
    menuType: 'M' as const,
    menuName: '操作日志',
    permission: 'system:log:list',
    path: '/system/log',
    component: 'system/log/page',
    icon: 'FileTextFilled',
    sort: 3,
    visible: 1,
    status: 1,
  },
  {
    id: 20,
    parentId: 19,
    menuType: 'B' as const,
    menuName: '删除日志',
    permission: 'system:log:delete',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  // 系统配置
  {
    id: 21,
    parentId: 1,
    menuType: 'M' as const,
    menuName: '系统配置',
    permission: 'system:config:list',
    path: '/system/config',
    component: 'system/config/page',
    icon: 'AdjustmentsFilled',
    sort: 4,
    visible: 1,
    status: 1,
  },
  {
    id: 22,
    parentId: 21,
    menuType: 'B' as const,
    menuName: '查询配置',
    permission: 'system:config:query',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 23,
    parentId: 21,
    menuType: 'B' as const,
    menuName: '创建配置',
    permission: 'system:config:create',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 24,
    parentId: 21,
    menuType: 'B' as const,
    menuName: '更新配置',
    permission: 'system:config:update',
    path: null,
    component: null,
    icon: null,
    sort: 2,
    visible: 1,
    status: 1,
  },
  {
    id: 25,
    parentId: 21,
    menuType: 'B' as const,
    menuName: '删除配置',
    permission: 'system:config:delete',
    path: null,
    component: null,
    icon: null,
    sort: 3,
    visible: 1,
    status: 1,
  },
  // 存储管理目录
  {
    id: 27,
    parentId: 0,
    menuType: 'D' as const,
    menuName: '存储管理',
    permission: null,
    path: null,
    component: null,
    icon: 'CloudFilled',
    sort: 1,
    visible: 1,
    status: 1,
  },
  // 存储配置
  {
    id: 28,
    parentId: 27,
    menuType: 'M' as const,
    menuName: '存储配置',
    permission: 'storage:config:list',
    path: '/storage/config',
    component: 'storage/config/page',
    icon: 'SettingsFilled',
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 29,
    parentId: 28,
    menuType: 'B' as const,
    menuName: '查询存储配置',
    permission: 'storage:config:query',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 30,
    parentId: 28,
    menuType: 'B' as const,
    menuName: '更新存储配置',
    permission: 'storage:config:update',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  // 文件管理
  {
    id: 31,
    parentId: 27,
    menuType: 'M' as const,
    menuName: '文件管理',
    permission: 'storage:file:list',
    path: '/storage/files',
    component: 'storage/files/page',
    icon: 'FolderFilled',
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 32,
    parentId: 31,
    menuType: 'B' as const,
    menuName: '文件列表',
    permission: 'storage:file:query',
    path: null,
    component: null,
    icon: null,
    sort: 0,
    visible: 1,
    status: 1,
  },
  {
    id: 33,
    parentId: 31,
    menuType: 'B' as const,
    menuName: '上传文件',
    permission: 'storage:file:upload',
    path: null,
    component: null,
    icon: null,
    sort: 1,
    visible: 1,
    status: 1,
  },
  {
    id: 34,
    parentId: 31,
    menuType: 'B' as const,
    menuName: '更新文件',
    permission: 'storage:file:update',
    path: null,
    component: null,
    icon: null,
    sort: 2,
    visible: 1,
    status: 1,
  },
  {
    id: 35,
    parentId: 31,
    menuType: 'B' as const,
    menuName: '删除文件',
    permission: 'storage:file:delete',
    path: null,
    component: null,
    icon: null,
    sort: 3,
    visible: 1,
    status: 1,
  },
]

/**
 * 角色菜单关联
 */
export const ROLE_MENUS: { roleId: number; menuId: number }[] = []

/**
 * 管理员角色关联
 */
export const ADMIN_ROLES: { adminId: number; roleId: number }[] = []

/**
 * 系统配置数据
 */
export const CONFIGS: NewSysConfig[] = []
